language: haskell
env:
  global:
  - secure: Cz5XOIWMrw3XgMUH0nLu2oiMDT2nns59t303gFpqjgckK2YBVgw2DXII4YwkvPypOccu6//3D0Pac1v3k3sIwpIUDnDVhnJufrbOYOjCqCnbHWdFy1pZW8TnzgVioWNIzYAiKs02axAt+bPkMMnr6OJAFMxy1EpJN2iFTU+VBM8=
  - secure: Sn6tMhxHs7D3ItP8KiCouTQ6ZTwocxp0Fp116o7dO0R6DCbZUhBTPvpvPez3r+yfaLjfh6jDfpFC+eiMnZrBuLp/VQVWwNn18CocW1wzLUa/6fYfl0vYIPc+/0Ostf5o3/psF2MhS/KCgc0ThbVvcPzUTsf3IxRF+4NhCs8NmyA=
install:
- cabal install hakyll
- sudo apt-get install s3cmd
script:
- ghc --make ./site.hs
- "./site build"
- echo "access_key = $AWS_ACCESS_KEY_ID" >> .s3cfg
- echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> .s3cfg
- tail .s3cfg
- "./travisupload.sh"
