language: haskell
env:
  global:
  - secure: W2sMCQLdYhjOXPaBaDii4TBN8XOe5XimGH0J7q0XwZHOw04G+QniYCRyXwdb3fSUGHKrT8eAYHSa50+uaCM0Z1tzjg6tdGn0IfBedcU/mWR7G/GpTxXygYQkGc1imNe3B8PawAarPc6J7uGALGw41+moZJpzr/hGLGQSjhskCK8=
  - secure: fDCLOFwjSnqftS3bdkCx2JPsXIOxWu7DM3VfjphBJMGVKx4Nf8VHN8IXjs4mRjWo51F41yJKI8KTsIhcqmQQLlFNPJ1k6WY8d2sZHGDjN2b7E28RUmurUeGT3GMxl8bk18QHuS7/HEiJQA4YdMuUOXaZ4HatKVHttHTdILDcZ5Y=
install:
- cabal install hakyll
- sudo apt-get install s3cmd
script:
- ghc --make ./site.hs
- "./site build"
- echo "access_key = $AWS_ACCESS_KEY_ID" >> .s3cfg
- echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> .s3cfg
- "./travisupload.sh"
