language: haskell
env:
  global:
    secure: "doWOQrOH/b/fxAu5f/T8nzH7OFeA4dxHgdEt+nquOnu/bIWrJbNFORZ1BDZqw/t0NTmha55CwtjwioTPhXb22B/AALjJsm9f5AGpqVwdr9OmiMekjYrAkVlAqk8zkl0/k+TkwhzRS9qf5
108PszwI9+Tu/wMSTybFZgzJqoclDY="
    secure: "T8QDE3CaaZmY0d4df3HhsX+WQtFlLWiHiIhjZim0KmPVlVRk7gG7EZbNYRBHU+mNu7Jh1Tri7j0QGjvPlepO57DYdSkx+0WSGbKIlbgzLhRK4EaoWooc9IUkNbH3uG7GDbLq0oexxN6+Y
pNE4TjKCPYym9roKuH8l0p1a9D6hxk="
install: 
  - cabal install hakyll
  - sudo apt-get install s3cmd
script:
  - ghc --make ./site.hs
  - ./site build
  - echo $AWS_ACCESS_KEY_ID >> .s3cfg
  - echo $AWS_SECRET_ACCESS_KEY >> .s3cfg
  - ./travisupload.sh
