language: haskell
env:
  global:
  - secure: Ms4M625v3kxV3oEtyBOGwKNVnmYNh4oF8zr1TLFjKCfcymSUf/36vwEj9ym+3X48gt7WTt4ytr3JNBPzVfVSE0rBjGrtJIWs5Pgs2jyq6FQeTvmh7PPRMKI5ne+BqksFE+CgaS20jqk2DFzfC+Wv6SK/CO6ykBLaU26VVS0cKzU=
  - secure: JVfS188jQ8AWs6pkHMze4vLrass7DWKVVnx632wwJO3Ws+ASyBd4JmwEdLg5M8C9FRI/1yO87M8lB24sWg2qrcGG9C7IrK1HuwRnuEJfxJ14eIQAKBJqwlS0FenvBAw30gU8rBzcassm2tcdN4TvmkFeQcspD69CjjZXVAnTw/w=
install:
- cabal install hakyll
- sudo apt-get install s3cmd
script:
- ghc --make ./site.hs
- "./site build"
- echo "access_key = $AWS_ACCESS_KEY_ID" >> .s3cfg
- echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> .s3cfg
- tail .s3cfg
- "./travisupload.sh"
