language: haskell
env:
  global:
  - secure: A1LQWuHx/l9kxPNfQhR+nC8uvjxsKeeU1jG4wdpGpJdO1u49OYiVBdk21miIero0bRGhOXB3thxPsTCwcxNzYX0Y/5mo2zAK6PdvlQhZROQbXWCr2Qm+TdSspEDN7B1qFXfhPZFdvc4tQE4L7zlCtxRfHQb7jRSrtRUEOlVin1c=
  - secure: Srfd2SvWN9jWdJl9yAlVFHArC8lg93b9lQwdwmL4H370HYm3YRboixVxpuZJTeifQ30YNVUCVwqUzuFRnOVp8kU2IkcifeDid7NijcPHt3YosTmIOC9a2ky2xdCoDXxps/AiNCTkPwkVHC8pWTQW/GpPytu6c2fw1zp1wM9smOM=
install:
- cabal install hakyll
- sudo apt-get install s3cmd
script:
- ghc --make ./site.hs
- "./site build"
- echo "access_key = $AWS_ACCESS_KEY_ID" >> .s3cfg
- echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> .s3cfg
- tail .s3cfg
- "./travisupload.sh"
